name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Java Jdk V8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'  # Ensure it includes jpackage

    - name: Install WiX Toolset
      run: choco install wixtoolset --no-progress

    - name: Grant jpackage access to WiX
      run: |
        $env:PATH += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
        echo "PATH=$env:PATH" >> $env:GITHUB_ENV

    - name: Build the app
      run: ./gradlew jar

    - name: Upload Jar artifact
      uses: actions/upload-artifact@v4
      with:
        name: FileCopier-installer
        path: build/libs/*
